### PR TITLE
adding a working Dockerfile

### PR DESCRIPTION
**Pull request by gekitsuu**

### CODE REVIEW

**Comment by mhall119** [comment]
When is the manage.py createsuperuser run? It's an interactive command and needs the user to specify a username, email and password

**Comment by gekitsuu** [comment]
Sorry! Didn't catch that it was failing. I moved it outside of the docker build step so the user can run it once they have a container running.

**Comment by mhall119** [comment]
This is great for local stuff, but manage.py runserver isn't adequate for a production deployment. We'll also need it to connect to a Postgresql server in a production deployment, and have a local-only settings file

**Comment by gekitsuu** [comment]
@mhall119 I can help solve both of those problems too :) do you have a preference about using Nginx or Apache in front of Django?. 

Re: the Postgres issue I'll modify the `settings.py` to pull from the environment variables for database settings if they are available. That way if someone runs the container locally (without passing any environment variables) then they will get the defaults like they do right now. If they want to run it against Postgres they pass the variables in, and the site will connect using those settings. If you haven't used docker containers this way before, it's a common pattern but not without some risk. If someone is able to hack the Django container they could read the environment variables and get your database username/password/hostname/etc. That risk is there using other methods too because you eventually have to store the settings in memory somewhere. Let me know if this sounds good and which web front end you'd like and I'll get to work on a new PR for those

**Comment by mhall119** [comment]
I know how to configure Apache to serve Django's static files without going through python, so that's what I usually use. If you know how to configure nginx to do the same, we can use that instead.

For Django deloyments, I usually create a local_settings.py file on the server that inherits from the settings.py in the source code, but then adds database settings and any other additions/overrides that the deployment needs. This is a pattern that works well for Django and gives a lot of flexibility to the admin deploying it. Can we do something similar using docker?

**Comment by gekitsuu** [comment]
You can't easily add files to a docker container without rebuilding it. We could explain how to apply an override file but that ends up looking a little strange when you use something like Kubernetes, Nomad, ECS, etc. to run the containers. I can set this up to be run via docker-compose which has some override abilities and we could use it to override the environment variables with local settings. For example the docker image by default works the way it does now but `docker-compose` can spin up a Postgres container with the Apache/Django container and connect the two for local dev. I don't mind setting that up so you can see what it's like then decide if that's a good solution or not. It doesn't represent a lot of effort but I probably won't get to it until later today

**Comment by mhall119** [comment]
Okay, let's try that. Worse case scenario we include a local_settings.py in the docker image that pulls from environment variables. That keeps the settings.py clean and simple and uses both of our other patterns

**Comment by mhall119** [comment]
Hey, check out Issue #12 I added an environ_settings.py that lets you override configs using environment variables, which should work for your docker needs

**Pull request merged**
