### PR TITLE
Add code formatter to enforce styleguide 

### LINKED ISSUE #180: Add code formatter to enforce styleguide
## Introduction

When working on a open source, it's a good practice to have linters and code formatters, to ensure a unified styleguide and therefore save time on code reviews.

Quoting [black](https://github.com/ambv/black):

> Black is the uncompromising Python code formatter. By using it, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.

> Blackened code looks the same regardless of the project you're reading. Formatting becomes transparent after a while and you can focus on the content instead.

> Black makes code review faster by producing the smallest diffs possible.

## Expected Behavior

Have a unified style guide, ensured by pre-commit hooks

## Proposed Solution

Use [Black](https://github.com/ambv/black) to format our code and [isort](https://github.com/timothycrosley/isort) to sort imports.

Pull request:  #181

### PR DESCRIPTION
**Pull request by thiagoferreiraw**
Closes #180 

## Introduction
Please view [issue description](#180 )

The files I explicit change were:

```
.pre-commit-config.yaml
README.md
setup.cfg
requirements.txt
```

All the other files were changed by black and isort, and therefore, since this pull request solves code formatting only, **no feature should've changed.**

### CODE REVIEW

**Comment by mhall119** [comment]
Does this run the black and isort on the local working set before committing? Is there anything that tells the user that their code is being changed so they're not surprised by it?

**Comment by mhall119** [comment]
Also, I use a virtualenv for development, so adding these dependencies to requirements.txt will only add them to my virtualenv, not to my host system

**Comment by thiagoferreiraw** [comment]
> Does this run the black and isort on the local working set before committing? Is there anything that tells the user that their code is being changed so they're not surprised by it?

[pre-commit](https://pre-commit.com/) works basically by checking your staged files. If the file is not conformant, it will reformat the file and stage it, so you can see the difference and stage/commit again. An example: 

image

But usually users tend to add the black and isort extension to the text editor (vscode, vim...), so it formats automatically on every save.

**Comment by thiagoferreiraw** [comment]
> Also, I use a virtualenv for development, so adding these dependencies to requirements.txt will only add them to my virtualenv, not to my host system

No problem, those dependences are only required for development. 

Since you mention it, do you have a different requirements.txt for production servers?

**Comment by mhall119** [comment]
There's only one requirements.txt, and I use the virtualenv for my development environment too so the pre-commit hook will need to be able to call Black from inside the virtualenv

**Comment by thiagoferreiraw** [comment]
@mhall119 , should not be a problem. Did you had a chance to checkout the branch and install the pre-commit hooks?

**Comment by mhall119** [comment]
So as long as you call `pre-commit install` from your virtualenv location, it will use your virtualenv whenever you call `git commit` even if you're not currently in it. That satisfied my development needs (and what the README recommends for developers)

**Pull request merged**
